### ISSUE TITLE
Support user directive to not run as root, only run one process

### ISSUE THREAD

**Issue by astubbs** [iloveicedgreentea/GoWatchIt#100]
**Is your feature request related to a problem? Please describe.**
The current Dockerfile includes Supervisor and a watcher script. While functional, this setup may not align with Docker best practices, such as one process per container and immutable containers. Additionally, the container currently runs as root, which introduces potential security risks.

**Describe the solution you’d like**

- Remove Supervisor and let Docker manage the main process (`/app`).
- Remove the watcher script (`watch.py`) as it’s unnecessary for immutable production containers.
- Run the container as a non-root user for improved security.
- Simplify the Dockerfile to focus on a single, secure process.
- Place executables in a subfolder like `/app/bin` instead of directly in the root directory for better organisation and adherence to standard file hierarchy.

**Additional context**
Would like to understand the original reasoning behind including Supervisor and the watcher script—was it intended primarily for development?

I’d be happy to help with a PR to make these changes if you’re open to it.

**Comment by iloveicedgreentea** [comment]
Supervisord is necessary for non orchestrated setups like unraid

the watcher script probably isnt needed anymore because configs are loaded per request

running as root isn’t a serious concern but feel free to make a pr to drop permissions

**Comment by astubbs** [comment]
Thanks for the clarification! I noticed in the Supervisor config that it’s managing two processes (/app and the watcher). If the watcher script isn’t necessary anymore, then the container would just be running one process (/app).

Could you clarify why supervisord is still required in this case? Is its inclusion specifically tied to Unraid being a non-orchestrated environment? From what I understand, even in Unraid, Docker itself handles single-process containers just fine using built-in restart policies. If supervisord was primarily added for managing multiple processes, removing the watcher might make it redundant.

I’d be happy to help with a PR to simplify the container by removing supervisord and relying on Docker’s native features, but I wanted to confirm if I’m missing any specific needs for Unraid. Let me know what you think!

**Comment by iloveicedgreentea** [comment]
Actually that’s a good point I forgot supervisord wasn’t managing nginx at all. I think it can be removed then

**Comment by iloveicedgreentea** [comment]
I removed supervisor
