### ISSUE TITLE
3rd party jellyfin plugin as mentioned on avs 

### ISSUE THREAD

**Issue by fattykidd** [iloveicedgreentea/GoWatchIt#45]
**_Log below, it includes a "play", "pause" and "stop" action._** 

?time="12-20-2023 23:43:57" level=debug msg="ProcessWebhook: Received valid multipart form" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:57"
                                                                                                                                          
time="12-20-2023 23:43:57" level=debug msg="decoding payload" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:60"
                                                                                                           
time="12-20-2023 23:43:57" level=error msg="Request has an invalid value in \"Account.id\" field at position 97" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:63"
                                                                                                                               
?time="12-20-2023 23:44:05" level=debug msg="ProcessWebhook: Received valid multipart form" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:57"
                                                                                                                              
time="12-20-2023 23:44:05" level=debug msg="decoding payload" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:60"
                                                                                               
time="12-20-2023 23:44:05" level=error msg="Request has an invalid value in \"Account.id\" field at position 98" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:63"
                                                                                                                   
?time="12-20-2023 23:44:09" level=debug msg="ProcessWebhook: Received valid multipart form" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:57"
                                                                                                                  
time="12-20-2023 23:44:09" level=debug msg="decoding payload" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:60"
                                                                                   
time="12-20-2023 23:44:09" level=error msg="Request has an invalid value in \"Account.id\" field at position 97" func=main.main.ProcessWebhook.func1 file="/go/src/app/handlers/plex_handler.go:63"

_**Below is the same "play", "pause" and "stop" sent to request bin for payload viewing.**_

 --55e75408-66b2-4847-9388-b99ae2db6145
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=payload

{"event":"media.play","user":true,"owner":true,"Account":{"id":"b700811125044bb5bbd2d9060e821870","title":"Fattykidd"},"Server":{"title":"Fatty\u0027s Jellyfin","uuid":"1d98a031c5154d30ad65e2fce3b20586"},"Player":{"local":true,"publicAddress":"192.168.50.53","title":"Chrome","uuid":"c443317b061d689735c11124eb9fc2d9"},"Metadata":{"librarySectionType":"movie","guid":"com.plexapp.agents.imdb://tt11858890?lang=en","title":"The Creator","type":"movie","parentTitle":"C","grandparentTitle":"Movies7","addedAt":1702078224,"updatedAt":1702078224,"year":2023,"duration":80090562}}
--55e75408-66b2-4847-9388-b99ae2db6145--

--3d105626-098e-4976-b926-fbf22d0948e6
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=payload

{"event":"media.pause","user":true,"owner":true,"Account":{"id":"b700811125044bb5bbd2d9060e821870","title":"Fattykidd"},"Server":{"title":"Fatty\u0027s Jellyfin","uuid":"1d98a031c5154d30ad65e2fce3b20586"},"Player":{"local":true,"publicAddress":"192.168.50.53","title":"Chrome","uuid":"c443317b061d689735c11124eb9fc2d9"},"Metadata":{"librarySectionType":"movie","guid":"com.plexapp.agents.imdb://tt11858890?lang=en","title":"The Creator","type":"movie","parentTitle":"C","grandparentTitle":"Movies7","addedAt":1702078224,"updatedAt":1702078224,"year":2023,"duration":80090562}}
--3d105626-098e-4976-b926-fbf22d0948e6--

--e335c11d-2bbc-40b1-8c50-9ee8e822cad0
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=payload

{"event":"media.stop","user":true,"owner":true,"Account":{"id":"b700811125044bb5bbd2d9060e821870","title":"Fattykidd"},"Server":{"title":"Fatty\u0027s Jellyfin","uuid":"1d98a031c5154d30ad65e2fce3b20586"},"Player":{"local":true,"publicAddress":"192.168.50.53","title":"Chrome","uuid":"c443317b061d689735c11124eb9fc2d9"},"Metadata":{"librarySectionType":"movie","guid":"com.plexapp.agents.imdb://tt11858890?lang=en","title":"The Creator","type":"movie","parentTitle":"C","grandparentTitle":"Movies7","addedAt":1702078224,"updatedAt":1702078224,"year":2023,"duration":80090562}}
--e335c11d-2bbc-40b1-8c50-9ee8e822cad0--

**Comment by iloveicedgreentea** [comment]
Its because plex sends account ID as int and this sends it as string. Is there a way to configure the account ID

**Comment by iloveicedgreentea** [comment]
You can try  ghcr.io/iloveicedgreentea/gowatchit:pr-36

Its completely untested at the moment, but let me know if the jellyfin thing works at least

**Comment by fattykidd** [comment]
**It's not loading beq profile. I'm not sure what I should be looking for in the log, I do see complaints about device uuid not matching.** 

time="12-21-2023 02:18:09" level=debug msg="decoding payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:62"
                     
utime="12-21-2023 02:18:09" level=debug msg="decodeWebhook: Received event: media.play" func=github.com/iloveicedgreentea/go-plex/internal/handlers.decodeWebhook file="/go/src/app/internal/handlers/plex_handler.go:48"
                                                               
time="12-21-2023 02:18:09" level=info msg="Got a request from UUID: c443317b061d689735c11124eb9fc2d9" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:70"
                                                                                                                        
time="12-21-2023 02:18:09" level=debug msg="ProcessWebhook:  Media type is: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:72"
                                                                                                                                                              
time="12-21-2023 02:18:09" level=debug msg="ProcessWebhook:  Media title is: The Creator" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:73"
                            _[GIN] 2023/12/21 - 02:18:09 | 200 |     543.261µs |      172.17.0.4 | POST     "/plexwebhook"
                                                                                                                          
>time="12-21-2023 02:18:09" level=debug msg="Current length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:81"
                                                                                                                                                         
time="12-21-2023 02:18:09" level=debug msg="Added length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:91"
      
time="12-21-2023 02:18:09" level=debug msg="Current length of plexChan in PlexWorker: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:698"
                                               
time="12-21-2023 02:18:09" level=debug msg="Sending new payload to eventRouter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:700"
                                                                               
time="12-21-2023 02:18:09" level=debug msg="filter '[]' does not match uuid 'c443317b061d689735c11124eb9fc2d9'" func=github.com/iloveicedgreentea/go-plex/internal/handlers.checkUUID file="/go/src/app/internal/handlers/plex_handler.go:464"
                                                                                                                                              
time="12-21-2023 02:18:09" level=info msg="Got a webhook but Client UUID 'c443317b061d689735c11124eb9fc2d9' does not match enabled filter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:479"
                                                           
time="12-21-2023 02:18:09" level=debug msg="eventRouter done processing payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:702"
                                                                                           

time="12-21-2023 02:19:16" level=debug msg="decoding payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:62"
                                                                                                             
time="12-21-2023 02:19:16" level=debug msg="decodeWebhook: Received event: media.pause" func=github.com/iloveicedgreentea/go-plex/internal/handlers.decodeWebhook file="/go/src/app/internal/handlers/plex_handler.go:48"
                                                                                                                                                       _[GIN] 2023/12/21 - 02:19:16 | 200 |     271.361µs |      172.17.0.4 | POST     "/plexwebhook"
                                                                      
time="12-21-2023 02:19:16" level=info msg="Got a request from UUID: c443317b061d689735c11124eb9fc2d9" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:70"
                                                                                                                               
time="12-21-2023 02:19:16" level=debug msg="ProcessWebhook:  Media type is: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:72"
                                                                                                                                                                     
time="12-21-2023 02:19:16" level=debug msg="ProcessWebhook:  Media title is: The Creator" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:73"
                                   
time="12-21-2023 02:19:16" level=debug msg="Current length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:81"
                                                                 
time="12-21-2023 02:19:16" level=debug msg="Added length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:91"
                                                                                             
time="12-21-2023 02:19:16" level=debug msg="Current length of plexChan in PlexWorker: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:698"
                                                                                                                                      
time="12-21-2023 02:19:16" level=debug msg="Sending new payload to eventRouter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:700"
                                                                                                                                                                      time="12-21-2023 02:19:16" level=debug msg="filter '[]' does not match uuid 'c443317b061d689735c11124eb9fc2d9'" func=github.com/iloveicedgreentea/go-plex/internal/handlers.checkUUID file="/go/src/app/internal/handlers/plex_handler.go:464"
                                                      time="12-21-2023 02:19:16" level=info msg="Got a webhook but Client UUID 'c443317b061d689735c11124eb9fc2d9' does not match enabled filter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:479"
                                                                                                                                                  time="12-21-2023 02:19:16" level=debug msg="eventRouter done processing payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:702"

**Comment by iloveicedgreentea** [comment]
>time="12-21-2023 02:19:16" level=info msg="Got a webhook but Client UUID 'c443317b061d689735c11124eb9fc2d9' does not match enabled filter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:479"

Your configured deviceUUIDFilter does not match what the webhook. What is it set to?

**Comment by fattykidd** [comment]
Device was left undefined.

**Comment by fattykidd** [comment]
As a test I entered the device uuid used above. We're making progress, it's now wanting me to check my whitelisted ip's.
I have entered my network gateway with /24 but the log remained the same as below.

time="12-21-2023 02:55:40" level=debug msg="decoding payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:62"
                 time="12-21-2023 02:55:40" level=debug msg="decodeWebhook: Received event: media.play" func=github.com/iloveicedgreentea/go-plex/internal/handlers.decodeWebhook file="/go/src/app/internal/handlers/plex_handler.go:48"
                                                          _[GIN] 2023/12/21 - 02:55:40 | 200 |      190.95µs |      172.17.0.4 | POST     "/plexwebhook"
                                                                                                                                                        time="12-21-2023 02:55:40" level=info msg="Got a request from UUID: c443317b061d689735c11124eb9fc2d9" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:70"
                                  time="12-21-2023 02:55:40" level=debug msg="ProcessWebhook:  Media type is: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:72"
                                                                        time="12-21-2023 02:55:40" level=debug msg="ProcessWebhook:  Media title is: Mission: Impossible - Dead Reckoning Part One" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:73"
                                                                                                                                                       time="12-21-2023 02:55:40" level=debug msg="Current length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:81"
      time="12-21-2023 02:55:40" level=debug msg="Added length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:91"
                                  time="12-21-2023 02:55:40" level=debug msg="Current length of plexChan in PlexWorker: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:698"
                                                                           time="12-21-2023 02:55:40" level=debug msg="Sending new payload to eventRouter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:700"
                                                                                                           time="12-21-2023 02:55:40" level=info msg="Processing media type: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:485"
                                                                                                                                     time="12-21-2023 02:55:40" level=error msg="Error authenticating with plex. Please check your IP whitelist" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:495"
                   time="12-21-2023 02:55:40" level=debug msg="eventRouter done processing payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:702"

**Comment by iloveicedgreentea** [comment]
Try whitelisting the docker ip range which is 172.16.0.0/16 by default I think I had to do that with unraid. Otherwise try adding the specific IP of the device. I found I had to add a few different things to whitelist to get it to work

I will release an update to allow a blank client filter but I don't recommend it because any device connected to your plex account will trigger stuff

**Comment by iloveicedgreentea** [comment]
please repull ghcr.io/iloveicedgreentea/gowatchit:pr-36 and see if that helps anything in addition to the above. I added a /logs endpoint to check the logs faster as well

**Comment by fattykidd** [comment]
Still battling with the "Check IP whitelist" 
time="12-22-2023 22:37:06" level=debug msg="decoding payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:62"
                 time="12-22-2023 22:37:06" level=debug msg="decodeWebhook: Received event: media.resume" func=github.com/iloveicedgreentea/go-plex/internal/handlers.decodeWebhook file="/go/src/app/internal/handlers/plex_handler.go:48"
                                                            time="12-22-2023 22:37:06" level=info msg="Got a request from UUID: c443317b061d689735c11124eb9fc2d9" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:70"
                                                                                                                     time="12-22-2023 22:37:06" level=debug msg="ProcessWebhook:  Media type is: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:72"
                                                                                                                                                           time="12-22-2023 22:37:06" level=debug msg="ProcessWebhook:  Media title is: Mission: Impossible - Dead Reckoning Part One" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:73"
                                                           ltime="12-22-2023 22:37:06" level=debug msg="Current length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:81"
                                                                                          time="12-22-2023 22:37:06" level=debug msg="Added length of plexChan: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.ProcessWebhook file="/go/src/app/internal/handlers/plex_handler.go:91"
                                                                                                                      [GIN] 2023/12/22 - 22:37:06 | 200 |     647.661µs |      172.17.0.3 | POST     "/plexwebhook"
                                    time="12-22-2023 22:37:06" level=debug msg="Current length of plexChan in PlexWorker: 0" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:700"
                                                                             time="12-22-2023 22:37:06" level=debug msg="Sending new payload to eventRouter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:702"
                                                                                                             time="12-22-2023 22:37:06" level=info msg="Processing media type: movie" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:487"
                                                                                                                                       time="12-22-2023 22:37:06" level=error msg="Error authenticating with plex. Please check your IP whitelist" func=github.com/iloveicedgreentea/go-plex/internal/handlers.eventRouter file="/go/src/app/internal/handlers/plex_handler.go:497"
                     time="12-22-2023 22:37:06" level=debug msg="eventRouter done processing payload" func=github.com/iloveicedgreentea/go-plex/internal/handlers.PlexWorker file="/go/src/app/internal/handlers/plex_handler.go:704"

**_Network Options available below._**

![Network Options 1](https://github.com/iloveicedgreentea/GoWatchIt/assets/120767778/17cd4715-36ef-4e0b-b218-4ac4b3658996)
![network options 2](https://github.com/iloveicedgreentea/GoWatchIt/assets/120767778/610e1cf8-bdb6-47c9-bef6-bff911385b14)
![network options 3](https://github.com/iloveicedgreentea/GoWatchIt/assets/120767778/50fd4199-64d8-4e8f-8b75-198023a4a5bc)
![network options 4](https://github.com/iloveicedgreentea/GoWatchIt/assets/120767778/19f8714c-1cbe-42ca-afd8-17f9d24c0674)

**Comment by newoski** [comment]
This is what he recommended for me when I had a similar issue in Unraid. Fixed my instance of that error


Try the following. If that works, take away one at a time to see which one breaks it I think the network the tool sees will be a docker subnet

(Shield ip),172.17.0.0/24,127.0.0.1/32

**Comment by iloveicedgreentea** [comment]
You need to add them to this section 
![image](https://github.com/iloveicedgreentea/GoWatchIt/assets/31193909/2358adcf-4bc1-492b-97b4-38c4687d200f)

**Comment by fattykidd** [comment]
That's going to be a problem. That section isn't present in the jellyfin ui.

**Comment by iloveicedgreentea** [comment]
Oh right I forgot you were using JF

Yeah BEQ will not work with JF until I implement the API. Might get it done by next week, will see how much time I have. In the meantime other functions might work but BEQ will not work as theres no way to currently get the codec

**Comment by fattykidd** [comment]
All good.. We're making progress. I forsee plenty of very happy jellyfin users once this gets ironed out.

**Comment by newoski** [comment]
@fattykidd so is this working now? I am contemplating a switch from Plex to Jellyfin

**Comment by fattykidd** [comment]
> @fattykidd so is this working now? I am contemplating a switch from Plex to Jellyfin

I believe we are waiting for ilan to add the jellyfin API to the code. 
I redeployed the latest container but it lacks a space for the jellyfin API key. 
Looking at the main page here it still says jellyfin support coming soon.

**Comment by iloveicedgreentea** [comment]
Its not going to work until the API is implemented. Working on that currently, almost done

**Comment by fattykidd** [comment]
> Its not going to work until the API is implemented. Working on that currently, almost done

Thank you for the confirmation. 
Are you going to switch it over to use the official plugin or is the 3rd party plugin going to work ? 
I tried nearly a dozen times last to install the official plugin and it comes back as "malfunctioned" every time. (Not your problem and I will proceed to open an issue with the jellyfin team if need be) but I have the 3rd party plugin installed and working on my system for all other needs.

**Comment by iloveicedgreentea** [comment]
Yeah it will use the official one. The other one does not send item ID 

FWIW it installed the first time for me

**Comment by fattykidd** [comment]
> Yeah it will use the official one. The other one does not send item ID
> 
> FWIW it installed the first time for me

My issue stemmed from a conflict with an existing email plugin I had installed. 
It's fixed now.

**Comment by iloveicedgreentea** [comment]
You are welcome to test it but I can't support it as I use it for my own testing and its not guaranteed to work

**Comment by fattykidd** [comment]
All good. Just wasn't sure where you were at with the API implementation. 
Will take it for a test run later.

**Comment by iloveicedgreentea** [comment]
I released 2.3.0. Still working on JF support but almost there.

**Comment by iloveicedgreentea** [comment]
[pr-54](https://github.com/users/iloveicedgreentea/packages/container/gowatchit/176806456?tag=pr-54)

This build "should" have some basic JF support. I tested it out and seems to work okay. Give it a shot if you have JF set up. It only works for play and stop at the moment but working on pause/resume because its totally different from how plex handles pause/resume.

**Comment by iloveicedgreentea** [comment]
docker pull ghcr.io/iloveicedgreentea/gowatchit:v2.3.2

This version should have full JF support. Pause/resume don't action anything because its super buggy. JF sends endless pause signals with incorrect info too, even when you start playing again so its just unsupportable. If that works I can make it a full release

**Comment by fattykidd** [comment]
Will check it out.

**Comment by iloveicedgreentea** [comment]
Any problems?

**Comment by fattykidd** [comment]
Haven't had a chance to test much. 
On first initial play event GoWatchIt saw the event but failed to trigger anything beyond logging the event. 
I am having an issue with my webhooks outside of GoWatchIt, it's not sending events reliably to home assistant or mqtt. I need to fix that before I can personally go further, I'm not sure if it's missing information in the template or something else. (I have it set to ignore the template and send all information)

**Comment by iloveicedgreentea** [comment]
can you try ghcr.io/iloveicedgreentea/gowatchit:pr-55

I think I finalized the extent of JF support I can reasonably do and added time based HDMI sync. Check the readme in the develop branch if you want to try it out.

**Comment by ThatRed** [comment]
Hi, I tested the "ghcr.io/iloveicedgreentea/gowatchit:pr-55" container and Jellyfin seems to work. It takes around 15s for the profile to be loaded. 

I can't figure out how to get the "Device UUID" for my nvidia shield. There is no "- "DeviceId\" or ""DeviceId\" in my JF logs. I tried to use the "Shield" device id from the "JF Admin Dashbord" under "Devices", but this causes "level=info msg="Got a webhook but Client UUID 'Android TV' does not match enabled filter" func=github.com/iloveicedgreentea/go-plex/internal/handlers.jfEventRouter file="/go/src/app/internal/handlers/jellyfin_handler.go:54"". I tried the id from the GoWatchIt log, but this didn't work either.

HDMI sync causes this error "level=error msg="Error pausing client: no active session found" func=github.com/iloveicedgreentea/go-plex/internal/common.WaitForHDMISync file="/go/src/app/internal/common/common.go:84"", but does not break JF. 

JF does not work, if "Use AVR For Codec Lookup" is activated. It looks like my Denon AVC-X3800H causes "panic: runtime error: slice bounds out of range [1:0]". 

MQTT without HA breaks it too: "level=error msg="Error on startup - unloading beq error connecting to topic - network Error : dial tcp: lookup http on 127.0.0.11:53: no such host" func=github.com/iloveicedgreentea/go-plex/internal/handlers.JellyfinWorker file="/go/src/app/internal/handlers/jellyfin_handler.go:358"" 

I don't know where "127.0.0.11:53" comes from and I'm not sure, if these errors are related to the JF functionality.

Thank you for your great work!

**Comment by iloveicedgreentea** [comment]
Thanks I will take a look at this eventually when I have time. webhooks don't action on pause because JF doesn't have a pause event

Your device ID should show up in the logs if you search for this string - \"DeviceId\ make sure its exactly the same. Enable debug logs and see if any info shows up
