### ISSUE TITLE
Whitelist for BEQ Authors

### ISSUE THREAD

**Issue by newoski** [iloveicedgreentea/GoWatchIt#46]
**Is your feature request related to a problem? Please describe.**
Going a step further than the existing BEQ Preferred Author option, a Whitelist would be a great way to ensure users can limit profiles to only those from a select group. Since there is no real screening process for BEQ submissions, having the option to only load BEQ files from authors that a user trusts would be fantastic. 

**Describe the solution you'd like**
Just like the BEQ Preferred Author field, a BEQ Author Whitelist field would accept author names and then only load BEQ files from those authors. This could be used in conjunction with BEQ Preferred Author -- assuming preferred author works in order of preference -- so that a user could limit their authors via Whitelist and then set a hierarchy of authors from most preferred to least preferred. 

**Describe alternatives you've considered**

**Additional context**

**Comment by iloveicedgreentea** [comment]
Will do , working on a new release which will include this

**Comment by fattykidd** [comment]
> Will do , working on a new release which will include this

Very happy about this.

**Comment by newoski** [comment]
Since ezBEQ doesn’t show the author of the loaded BEQ file, it will be likely necessary to include in debug logs the author of the BEQ file being loaded
