### ISSUE TITLE
"beq profile was not found in catalog" in v2.1.9, but works in v0.0.7

### ISSUE THREAD

**Issue by chippoman** [iloveicedgreentea/GoWatchIt#49]
Playing "Pirates of the Carribean: Curse of the Black Pearl" in Atmos (TRUEHD 7.1) with v2.1.9. Confirmed that a beq profile exists in the repository, but getting "beq profile was not found in catalog" error.

> time="01-02-2024 21:00:03" level=debug msg="Event Router: media.resume received"
> time="01-02-2024 21:00:03" level=error msg="error connecting to topic - network Error : dial tcp: missing address"
> time="01-02-2024 21:00:03" level=debug msg="Unloading ezBEQ profiles"
> time="01-02-2024 21:00:03" level=debug msg="using endpoint /api/1/devices/master/filter/1"
> time="01-02-2024 21:00:03" level=debug msg="Using method DELETE"
> time="01-02-2024 21:00:03" level=debug msg="Header is set to false"
> time="01-02-2024 21:00:03" level=debug msg="Using url http://192.168.0.148:8080/api/1/devices/master/filter/1"
> time="01-02-2024 21:00:03" level=debug msg="Headers from req map[]"
> time="01-02-2024 21:00:05" level=error msg="Error on startup - unloading beq error connecting to topic - network Error : dial tcp: missing address"
> time="01-02-2024 21:00:05" level=debug msg="getPlexMovieDb: Got tmdb ID from plex - tmdb://22"
> time="01-02-2024 21:00:05" level=debug msg="beq payload is &models.SearchRequest{TMDB:\"22\", Year:2003, Codec:\"\", PreferredAuthor:\"\", Edition:\"\", SkipSearch:true, EntryID:\"\", MVAdjust:0, DryrunMode:false, MediaType:\"movie\", Devices:[]string{\"master\"}, Slots:[]int{1}}"
> time="01-02-2024 21:00:05" level=debug msg="sending ezbeq search request to /api/1/search?audiotypes=&years=2003"
> time="01-02-2024 21:00:05" level=debug msg="Using method GET"
> time="01-02-2024 21:00:05" level=debug msg="Header is set to false"
> time="01-02-2024 21:00:05" level=debug msg="Using url http://192.168.0.148:8080/api/1/search?audiotypes=&years=2003"
> time="01-02-2024 21:00:05" level=debug msg="Headers from req map[]"
> time="01-02-2024 21:00:05" level=error msg="beq profile was not found in catalog"
> time="01-02-2024 21:00:05" level=debug msg="eventRouter done processing payload"

Downgrade to v0.0.7 (with the same config.json file) and it works:

> time="01-02-2024 16:05:21" level=debug msg="Started in debug mode..."
> time="01-02-2024 16:05:21" level=info msg="Starting server"
> time="01-02-2024 16:05:21" level=info msg="PlexWorker started"
> time="01-02-2024 16:05:21" level=info msg="Minidsp worker started"
> time="01-02-2024 16:05:21" level=info msg="Started with ezbeq enabled"
> time="01-02-2024 16:05:21" level=debug msg="Started minidsp worker with ezbeq"
> time="01-02-2024 16:05:22" level=debug msg="Unloading ezBEQ profile"
> time="01-02-2024 16:06:16" level=debug msg="decodeWebhook: Received event: media.pause"
> time="01-02-2024 16:06:16" level=debug msg="!!! Your Player UUID is 0d3b37f7-6ee8-42dd-933f-7432e19763e1 !!!!!"
> time="01-02-2024 16:06:16" level=debug msg="ProcessWebhook:  Media type is: movie"
> time="01-02-2024 16:06:16" level=debug msg="ProcessWebhook:  Media title is: Pirates of the Caribbean: The Curse of the Black Pearl"
> time="01-02-2024 16:06:16" level=info msg="Processing media type: movie"
> time="01-02-2024 16:06:16" level=debug msg="Event Router: Found edition: "
> time="01-02-2024 16:06:16" level=debug msg="Event Router: Getting codec from data"
> time="01-02-2024 16:06:16" level=debug msg="Codecs from plex received: English (TRUEHD 7.1), TrueHD Atmos 7.1 (English)"
> time="01-02-2024 16:06:16" level=debug msg="Atmos: true - DD+: false"
> time="01-02-2024 16:06:16" level=debug msg="Event Router: Received codec: Atmos"
> time="01-02-2024 16:06:16" level=debug msg="Event Router: Got media type of: movie "
> time="01-02-2024 16:06:16" level=debug msg="Event Router: media.pause received"
> time="01-02-2024 16:06:16" level=debug msg="Unloading ezBEQ profile"
> time="01-02-2024 16:06:18" level=debug msg="decodeWebhook: Received event: media.resume"
> time="01-02-2024 16:06:18" level=debug msg="!!! Your Player UUID is 0d3b37f7-6ee8-42dd-933f-7432e19763e1 !!!!!"
> time="01-02-2024 16:06:18" level=debug msg="ProcessWebhook:  Media type is: movie"
> time="01-02-2024 16:06:18" level=debug msg="ProcessWebhook:  Media title is: Pirates of the Caribbean: The Curse of the Black Pearl"
> time="01-02-2024 16:06:18" level=info msg="Processing media type: movie"
> time="01-02-2024 16:06:18" level=debug msg="Event Router: Found edition: "
> time="01-02-2024 16:06:18" level=debug msg="Event Router: Getting codec from data"
> time="01-02-2024 16:06:18" level=debug msg="Codecs from plex received: English (TRUEHD 7.1), TrueHD Atmos 7.1 (English)"
> time="01-02-2024 16:06:18" level=debug msg="Atmos: true - DD+: false"
> time="01-02-2024 16:06:18" level=debug msg="Event Router: Received codec: Atmos"
> time="01-02-2024 16:06:18" level=debug msg="Event Router: Got media type of: movie "
> time="01-02-2024 16:06:18" level=debug msg="Event Router: media.resume received"
> time="01-02-2024 16:06:18" level=debug msg="Unloading ezBEQ profile"
> time="01-02-2024 16:06:20" level=debug msg="getPlexMovieDb: Got tmdb ID from plex - tmdb://22"
> time="01-02-2024 16:06:20" level=debug msg="sending ezbeq search request to /api/1/search?audiotypes=Atmos&years=2003"
> time="01-02-2024 16:06:20" level=debug msg="Beq results: {4653973ba94bbafb0625c7b8a2990231264f9473_142 bad boys ii 2003 [Atmos] 1a83bc66fd9b5a18c3751a72e47265e7ea52dfd412c84a0eea30d71156aeea9d -0.5  8961}"
> 
> [... snip ...]
> 
> time="01-02-2024 16:06:20" level=debug msg="Beq results: {4653973ba94bbafb0625c7b8a2990231264f9473_6838 pirates of the caribbean the curse of the black pearl 2003 [Atmos] 3575ee10e459d883a0fe4b49cd909326ec4e563cb41064202c062cdc4ed544c2 0  22}"
> time="01-02-2024 16:06:20" level=debug msg="sending BEQ payload: models.BeqPatchV2{Mute:false, MasterVolume:0, Slots:[]models.SlotsV2{models.SlotsV2{ID:\"1\", Active:true, Gains:[]float64{0, 0}, Mutes:[]bool{false, false}, Entry:\"4653973ba94bbafb0625c7b8a2990231264f9473_6838\"}}}"
> time="01-02-2024 16:06:20" level=debug msg="json payload {\"mute\":false,\"masterVolume\":0,\"slots\":[{\"id\":\"1\",\"active\":true,\"gains\":[0,0],\"mutes\":[false,false],\"entry\":\"4653973ba94bbafb0625c7b8a2990231264f9473_6838\"}]}"
> time="01-02-2024 16:06:20" level=debug msg="using endpoint /api/2/devices/master"

My config.json:

```
{
  "ezbeq": {
    "adjustmastervolumewithprofile": true,
    "denonip": "",
    "denonport": "",
    "dryrun": false,
    "enabled": true,
    "enabletvbeq": true,
    "notifyendpointname": "",
    "notifyonload": true,
    "port": "8080",
    "preferredauthor": "",
    "slots": [
      1
    ],
    "stopplexifmismatch": false,
    "url": "http://192.168.0.148",
    "useavrcodecsearch": false
  },
  "homeassistant": {
    "enabled": false,
    "pausescriptname": "",
    "playscriptname": "",
    "port": "",
    "remoteentityname": "",
    "stopscriptname": "",
    "token": "",
    "triggeraspectratiochangeonevent": false,
    "triggeravrmastervolumechangeonevent": false,
    "triggerlightsonevent": false,
    "url": ""
  },
  "main": {
    "listenport": "9999"
  },
  "mqtt": {
    "password": "",
    "topicaspectratio": "",
    "topicbeqcurrentprofile": "",
    "topiclights": "",
    "topicminidspmutestatus": "",
    "topicplayingstatus": "",
    "topicvolume": "",
    "url": "",
    "username": ""
  },
  "plex": {
    "deviceuuidfilter": "0d3b37f7-6ee8-42dd-933f-7432e19763e1",
    "enabled": true,
    "enabletrailersupport": false,
    "ownernamefilter": "myownername",
    "playerip": "",
    "playermachineidentifier": "",
    "port": "32400",
    "token": "PLACEHOLDER for future use",
    "url": "http://192.168.0.99"
  },
  "signal": {
    "enabled": false,
    "source": ""
  }
}
```

**Comment by chippoman** [comment]
I think this is the same issue as reported by someone else here: https://www.avsforum.com/threads/gowatchit-beq-ezbeq-plex-jellyfin-theater-automation-official-thread.3264800/post-62777949 where the audio codec not getting parsed?

**Comment by chippoman** [comment]
It looks like it was fixed between 2.1.9 and the current commits.

When I pulled from github and rebuilt from source it's working as expected.

**Comment by iloveicedgreentea** [comment]
cool I probably fixed it along the way as I have been working on bugs. master "should" be stable or you can try the [pr-36](https://github.com/users/iloveicedgreentea/packages/container/gowatchit/161591560?tag=pr-36) image until I do the next release

**Comment by chippoman** [comment]
Spoke too soon. Both the current master branch and pr-36 tag detect the audio codec correctly again, but for some reason, they both think that the ezbeq config is set to disabled:

My config.json (enabled for ezbeq is true):

> / # cat data/config.json
> {
>   "ezbeq": {
>     "adjustmastervolumewithprofile": true,
>     "denonip": "192.168.0.60",
>     "denonport": "23",
>     "dryrun": false,
>     "enabled": true,
>     "enabletvbeq": true,
>     "notifyendpointname": "",
>     "notifyonload": true,
>     "port": "8080",
>     "preferredauthor": "",

But no payload is sent to ezbeq: 

> time="01-03-2024 03:26:26" level=debug msg="Codecs from plex received: English (TRUEHD 7.1), TrueHD Atmos 7.1 (English)"
> time="01-03-2024 03:26:26" level=debug msg="Atmos: true - DD+: false"
> time="01-03-2024 03:26:26" level=debug msg="Codecs from plex received: Atmos, "
> time="01-03-2024 03:26:26" level=debug msg="Atmos: true - DD+: false"
> time="01-03-2024 03:26:26" level=debug msg="Found codec: stereo\r"
> time="01-03-2024 03:26:26" level=debug msg="getPlexMovieDb: Got tmdb ID from plex - tmdb://22"
> time="01-03-2024 03:26:26" level=debug msg="BEQ is disabled, skipping"
> time="01-03-2024 03:26:26" level=info msg="BEQ profile loaded"
> time="01-03-2024 03:26:26" level=debug msg="Waiting for goroutines"

**Comment by iloveicedgreentea** [comment]
typo on my part when I was refactoring. Should be fixed in master now
