### ISSUE TITLE
Please enable TZ to work in docker

### ISSUE THREAD

**Issue by douginoz** [iloveicedgreentea/GoWatchIt#67]
Currently, the docker instance uses UTC time and totally ignores the docker TZ setting.  Even if I go into the shell and set TZ, it's ignored.  Apparently the tzdata package needs to be installed to make it use TZ.

The impact right now is that the log files show a different date and time which makes it a pain to correlate to local activities.

**Comment by iloveicedgreentea** [comment]
v2.3.4 supports overriding TZ with the TZ env var
